pipeline:
  name: "Centralized Data Pipeline"
  version: "1.0.0"
  description: "ETL pipeline — sources: MySQL to DataFrame"

fg_nakes:
  feedname: fg_nakes
  developer: bai
  sources:
    - id: nakes
      type: mysql
      connection: mysql_main
      query: "SELECT * FROM dc_nakes"
  
  target:
    type: csv
    path: /data/output/nakes.csv
    delimiter: "|"
    header: False

fg_pegawai:
  feedname: fg_pegawai
  developer: bai
  sources:
    - id: pegawai
      type: mysql
      connection: mysql_main
      query: "SELECT * FROM dc_pegawai"
  
  transform:
    filter:
      - column: agama
        op: notnull

fg_pasien_with_bill:
  feedname: fg_pasien_with_bill
  developer: bai
  sources:
    - id: pendaftaran
      type: mysql
      connection: mysql_main
      query: "select id, id_pasien from dc_pendaftaran"

    - id: layanan_pendaftaran
      type: mysql
      connection: mysql_main
      query: "select id, id_pendaftaran, id_dokter, cara_bayar, terklaim, status from dc_layanan_pendaftaran"

  join:
    left: pendaftaran        
    right: layanan_pendaftaran     
    how: left              
    "on":
      left: id
      right: id_pendaftaran
                    
  transform:
    filter:
      - column: id_pendaftaran
        op: notnull

  target:
    type: mysql
    connection: mysql_main
    table: output_table
    if_exists: replace